CREATE DATABASE DINOS_DONUTS

USE DINOS_DONUTS
CREATE TABLE CLIENTE(
    ID INT IDENTITY (1,1) NOT NULL,
    NOME VARCHAR (50) NOT NULL,
    CPF VARCHAR (15) NOT NULL,
    DATANASCIMENTO DATE NOT NULL,
    PONTOSFIDELIDADE INT NOT NULL

    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)

)
USE DINOS_DONUTS
CREATE TABLE PRODUTO(
    ID INT IDENTITY (1,1) NOT NULL,
    DESCRICAO VARCHAR (150) NOT NULL,
    PRECO FLOAT NOT NULL,
    VALIDADE DATE NOT NULL,
    ATIVO BIT NOT NULL,
    QUANTIDADE INT NOT NULL
    
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
)

USE DINOS_DONUTS
CREATE TABLE PEDIDO(
    ID INT IDENTITY (1,1) NOT NULL,
    CLIENTE INT NULL,
    PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALORTOTAL FLOAT NOT NULL,
    DATAPEDIDO DATETIME NOT NULL,
    STATUSPEDIDO INT NOT NULL,

 CONSTRAINT PK_PEDIDO PRIMARY KEY (ID),
 CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID),
 CONSTRAINT FK_PRODUTO FOREIGN KEY (PRODUTO) REFERENCES PRODUTO(ID)


)




